GGYatirim/Controllers/ilanlarController.cs
using GGYatirim.Models.Sinif;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.EntityFrameworkCore;


namespace GGYatirim.Controllers
{
    [AllowAnonymous]
    public class ilanlarController : Controller
    {
        GYatirimEntities dr = new GYatirimEntities();
        // GET: ilanlar


        // Apartman


        [Route("Tumilanlar")]
        public ActionResult Apartman()
        {
            var deger = dr.Dbilan.Where(k => k.Durum == true && k.MOnay == true).OrderByDescending(l => l.ilanID).ToList();
            return View(deger);
        }

        // Daire

        public ActionResult Daire(string p, int sayfa = 1)
        {
            //  var d1 = dr.Dbilan.Where(f => f.Durum == true).Where(f => f.ilanDurumIDD == 1).ToList();
            // var d1 = dr.Dbilan.Where(k => k.Durum == true && k.MOnay == true).OrderByDescending(l => l.ilanID).ToList();
            // return View(d1);

            var sonuc = from s in dr.Dbilan.Where(k => k.Durum == true && k.MOnay == true).OrderByDescending(f => f.ilanID) select s;
            if (!string.IsNullOrEmpty(p))
            {
                sonuc = sonuc.Where(s => s.ilanNo.Contains(p.ToLower()) || s.EmlakTipi.Contains(p.ToLower())
                || s.Aciklama.Contains(p.ToLower()) || s.DbEmlakTipi.EmlakTipAd.Contains(p.ToLower())
                || s.DbilanDurum.ilanDurumAd.Contains(p.ToLower()));
            }


            return View(sonuc.ToList().ToPagedList(sayfa, 6));
        }



        // Arsa

        public ActionResult Arsa(string p, int sayfa = 1)
        {

            //var d1 = dr.Dbilan.Where(k => k.Durum == true && k.MOnay == true).OrderByDescending(l => l.ilanID).ToList();
            //return View(d1);

            var sonuc = from s in dr.Dbilan.Where(k => k.Durum == true && k.MOnay == true).OrderByDescending(f => f.ilanID) select s;
            if (!string.IsNullOrEmpty(p))
            {
                sonuc = sonuc.Where(s => s.ilanNo.Contains(p.ToLower()) || s.EmlakTipi.Contains(p.ToLower())
                || s.Aciklama.Contains(p.ToLower()) || s.DbEmlakTipi.EmlakTipAd.Contains(p.ToLower())
                || s.DbilanDurum.ilanDurumAd.Contains(p.ToLower()));
            }


            return View(sonuc.ToList().ToPagedList(sayfa, 6));
        }

        // Müstakil

        public ActionResult Mustakil(string p, int sayfa = 1)
        {
            var sonuc = from s in dr.Dbilan.Where(k => k.Durum == true && k.MOnay == true).OrderByDescending(f => f.ilanID) select s;
            if (!string.IsNullOrEmpty(p))
            {
                sonuc = sonuc.Where(s => s.ilanNo.Contains(p.ToLower()) || s.EmlakTipi.Contains(p.ToLower())
                || s.Aciklama.Contains(p.ToLower()) || s.DbEmlakTipi.EmlakTipAd.Contains(p.ToLower())
                || s.DbilanDurum.ilanDurumAd.Contains(p.ToLower()));
            }


            return View(sonuc.ToList().ToPagedList(sayfa, 6));
        }



        // Dubleks
        public ActionResult Dubleks(string p, int sayfa = 1)
        {
            var sonuc = from s in dr.Dbilan.Where(k => k.Durum == true && k.MOnay == true).OrderByDescending(f => f.ilanID) select s;
            if (!string.IsNullOrEmpty(p))
            {
                sonuc = sonuc.Where(s => s.ilanNo.Contains(p.ToLower()) || s.EmlakTipi.Contains(p.ToLower())
                || s.Aciklama.Contains(p.ToLower()) || s.DbEmlakTipi.EmlakTipAd.Contains(p.ToLower())
                || s.DbilanDurum.ilanDurumAd.Contains(p.ToLower()));
            }


            return View(sonuc.ToList().ToPagedList(sayfa, 6));
        }



        // Arazi 6
        public ActionResult Arazi(string p, int sayfa = 1)
        {
            var sonuc = from s in dr.Dbilan.Where(k => k.Durum == true && k.MOnay == true).OrderByDescending(f => f.ilanID) select s;
            if (!string.IsNullOrEmpty(p))
            {
                sonuc = sonuc.Where(s => s.ilanNo.Contains(p.ToLower()) || s.EmlakTipi.Contains(p.ToLower())
                || s.Aciklama.Contains(p.ToLower()) || s.DbEmlakTipi.EmlakTipAd.Contains(p.ToLower())
                || s.DbilanDurum.ilanDurumAd.Contains(p.ToLower()));
            }


            return View(sonuc.ToList().ToPagedList(sayfa, 6));
        }

        // Dükkan 7
        public ActionResult Dukkan(string p, int sayfa = 1)
        {
            //  var d1 = dr.Dbilan.Where(k => k.Durum == true && k.MOnay == true).OrderByDescending(l => l.ilanID).ToList();
            // return View(d1);
            var sonuc = from s in dr.Dbilan.Where(k => k.Durum == true && k.MOnay == true).OrderByDescending(f => f.ilanID) select s;
            if (!string.IsNullOrEmpty(p))
            {
                sonuc = sonuc.Where(s => s.ilanNo.Contains(p.ToLower()) || s.EmlakTipi.Contains(p.ToLower())
                || s.Aciklama.Contains(p.ToLower()) || s.DbEmlakTipi.EmlakTipAd.Contains(p.ToLower())
                || s.DbilanDurum.ilanDurumAd.Contains(p.ToLower()));
            }


            return View(sonuc.ToList().ToPagedList(sayfa, 6));
        }


        // İşyeri 8
        public ActionResult isyeri(string p, int sayfa = 1)
        {
            //  var d1 = dr.Dbilan.Where(k => k.Durum == true && k.MOnay == true).OrderByDescending(l => l.ilanID).ToList();
            // return View(d1);
            var sonuc = from s in dr.Dbilan.Where(k => k.Durum == true && k.MOnay == true).OrderByDescending(f => f.ilanID) select s;
            if (!string.IsNullOrEmpty(p))
            {
                sonuc = sonuc.Where(s => s.ilanNo.Contains(p.ToLower()) || s.EmlakTipi.Contains(p.ToLower())
                || s.Aciklama.Contains(p.ToLower()) || s.DbEmlakTipi.EmlakTipAd.Contains(p.ToLower())
                || s.DbilanDurum.ilanDurumAd.Contains(p.ToLower()));
            }


            return View(sonuc.ToList().ToPagedList(sayfa, 6));
        }


        // Bahçe 9
        public ActionResult Bahce(string p, int sayfa = 1)
        {
            var sonuc = from s in dr.Dbilan.Where(k => k.Durum == true && k.MOnay == true).OrderByDescending(f => f.ilanID) select s;
            if (!string.IsNullOrEmpty(p))
            {
                sonuc = sonuc.Where(s => s.ilanNo.Contains(p.ToLower()) || s.EmlakTipi.Contains(p.ToLower())
                || s.Aciklama.Contains(p.ToLower()) || s.DbEmlakTipi.EmlakTipAd.Contains(p.ToLower())
                || s.DbilanDurum.ilanDurumAd.Contains(p.ToLower()));
            }


            return View(sonuc.ToList().ToPagedList(sayfa, 6));
        }


        // Petrol İstasyonu 10
        public ActionResult Petrolistasyon(string p, int sayfa = 1)
        {
            var sonuc = from s in dr.Dbilan.Where(k => k.Durum == true && k.MOnay == true).OrderByDescending(f => f.ilanID) select s;
            if (!string.IsNullOrEmpty(p))
            {
                sonuc = sonuc.Where(s => s.ilanNo.Contains(p.ToLower()) || s.EmlakTipi.Contains(p.ToLower())
                || s.Aciklama.Contains(p.ToLower()) || s.DbEmlakTipi.EmlakTipAd.Contains(p.ToLower())
                || s.DbilanDurum.ilanDurumAd.Contains(p.ToLower()));
            }


            return View(sonuc.ToList().ToPagedList(sayfa, 6));
        }


        // Çiftlik 11
        public ActionResult Ciftlik(string p, int sayfa = 1)
        {
            var sonuc = from s in dr.Dbilan.Where(k => k.Durum == true && k.MOnay == true).OrderByDescending(f => f.ilanID) select s;
            if (!string.IsNullOrEmpty(p))
            {
                sonuc = sonuc.Where(s => s.ilanNo.Contains(p.ToLower()) || s.EmlakTipi.Contains(p.ToLower())
                || s.Aciklama.Contains(p.ToLower()) || s.DbEmlakTipi.EmlakTipAd.Contains(p.ToLower())
                || s.DbilanDurum.ilanDurumAd.Contains(p.ToLower()));
            }


            return View(sonuc.ToList().ToPagedList(sayfa, 6));
        }


        // Ahır 12
        public ActionResult Ahir(string p, int sayfa = 1)
        {
            var sonuc = from s in dr.Dbilan.Where(k => k.Durum == true && k.MOnay == true).OrderByDescending(f => f.ilanID) select s;
            if (!string.IsNullOrEmpty(p))
            {
                sonuc = sonuc.Where(s => s.ilanNo.Contains(p.ToLower()) || s.EmlakTipi.Contains(p.ToLower())
                || s.Aciklama.Contains(p.ToLower()) || s.DbEmlakTipi.EmlakTipAd.Contains(p.ToLower())
                || s.DbilanDurum.ilanDurumAd.Contains(p.ToLower()));
            }


            return View(sonuc.ToList().ToPagedList(sayfa, 6));
        }


        // Otomobil 13
        public ActionResult Otomobil(string p, int sayfa = 1)
        {
            var sonuc = from s in dr.Dbilan.Where(k => k.Durum == true && k.MOnay == true).OrderByDescending(f => f.ilanID) select s;
            if (!string.IsNullOrEmpty(p))
            {
                sonuc = sonuc.Where(s => s.ilanNo.Contains(p.ToLower()) || s.EmlakTipi.Contains(p.ToLower())
                || s.Aciklama.Contains(p.ToLower()) || s.DbEmlakTipi.EmlakTipAd.Contains(p.ToLower())
                || s.DbilanDurum.ilanDurumAd.Contains(p.ToLower()));
            }


            return View(sonuc.ToList().ToPagedList(sayfa, 6));
        }


        // Traktör 14
        public ActionResult Traktor(string p, int sayfa = 1)
        {
            var sonuc = from s in dr.Dbilan.Where(k => k.Durum == true && k.MOnay == true).OrderByDescending(f => f.ilanID) select s;
            if (!string.IsNullOrEmpty(p))
            {
                sonuc = sonuc.Where(s => s.ilanNo.Contains(p.ToLower()) || s.EmlakTipi.Contains(p.ToLower())
                || s.Aciklama.Contains(p.ToLower()) || s.DbEmlakTipi.EmlakTipAd.Contains(p.ToLower())
                || s.DbilanDurum.ilanDurumAd.Contains(p.ToLower()));
            }


            return View(sonuc.ToList().ToPagedList(sayfa, 6));
        }


        // İlan Ara
        // Çalışmıyor
        public PartialViewResult ilanAra(string p)
        {

GGYatirim/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="#2c2c2c">
    <meta name="msapplication-navbutton-color" content="#2c2c2c">
    <meta name="apple-mobile-web-app-status-bar-style" content="#2c2c2c">
    <title>Satlyk, Karende, Awtoulag  &#8211;  Webigem Satylyk Karende Jaylar Awtomobiller</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="robots" content="index, follow" />
    <meta name="keywords" content="emlak fiyatları, 2.el oto, ikinci el araba fiyatları, ücretsiz ilan, apartman, daire, arsa, müstakil, dubleks, arazi, dükkan,işyeri, bahçe, petrol istasyonu, çiftlik, ahır, ücretsiz emlak ilan, ücretsiz oto ilan" />
    <meta name="description" content="1992 yılında kurulan Güner Group Yatırım, satılık, kiralık, ikinci el, otomobil, apartman, daire, arsa, müstakil, dubleks, arazi, dükkan, işyeri, bahçe, petrol istasyonu, çiftlik, ahır ve her türlü ürün - ücretsiz ilan sitesi." />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta name="publisher" content="gunergroupyatirim.com" />
    <meta name="copyright" content="gunergroupyatirim ®" />
    <meta name="date-creation-yyyy" content="2022" />
    <meta name="classification" content="Machine" />
    <meta name="author" content="Türkiye’nin önde gelen şirketlerinden biridir. 30 yıllık tecrübe ile Müşteri memnuniyeti odaklı hizmet politikası , her zaman güncel geniş portföyü,gayrimenkul,satılık, kiralık, ikinci el, otomobil, emlak ve her türlü ürün - ücretsiz ilan platformudur. Öncesi ve sonrası danışmanlığı ile emlak sektöründe güvenirliliği ve hizmet kalitesi ile isim yapmış bir firmadır." />
    <meta name="rating" content="all" />
    <meta name="expires" content="no" />
    <meta name="language" content="TR" />
    <meta name="distribution" content="global" />
    <meta name="rating" content="all" />
    <meta name="googlebot" content="NOODP" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="pragma" content="no-cache" />
    <meta name="revisit-after" content="1 Day" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="GENERATOR" content="gunergroupyatirim.com" />
    <meta name="RESOURCE-TYPE" content="DOCUMENT" />
    <meta name="DISTRIBUTION" content="GLOBAL" />
    <meta name="ROBOTS" content="INDEX, FOLLOW" />
    <meta name="REVISIT-AFTER" content="1 DAYS" />
    <meta name="RATING" content="GENERAL" />
    <meta http-equiv="PAGE-ENTER" content="RevealTrans(Duration=0,Transition=1)" />
    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="Gunergroupyatirim satılık, kiralık, ikinci el, otomobil, emlak ve her türlü ürün - ücretsiz ilan ver San. A.Ş" />
    <meta property="og:url" content="https://webigem.site/" />
    <meta property="og:title" content="Güner Group &#8211; For Sale, Rent, Real Estate, Auto, Shopping Products| All Ad Types" />
    <meta property="og:description" content="Güner Group Investment, founded in 1992, is a free classifieds and online shopping site for sale, rental, second hand, automobile, real estate and all kinds of products." />
    <meta property="og:image" content="~/Content/Images/favicon-01.png" />
    <link rel="canonical" href="https://webigem.site/" />
    <link rel="icon" href="~/Content/Images/favicon-01.png" sizes="32x32" />
    <link rel="icon" href="~/Content/Images/favicon-01.png" sizes="192x192" />
    <link rel="apple-touch-icon-precomposed" href="~/Content/Images/favicon-01.png" />
    <meta name="msapplication-TileImage" content="~/Content/Images/favicon-01.png" />
    <link href="~/area/builds/area/css/style.min.css" rel="stylesheet" />
    <link href="~/area/css-min/area.min.css" rel="stylesheet" />
</head>

<body>
    @*<div id="preloader">
            <div>
                <canvas id='circleback' height='100' width='100'></canvas>
                <canvas id='circlemain' height='100' width='100'></canvas>
            </div>
        </div>*@

    <div class="top-bar">
        <div class="container">
            <div class="contacts-wrapper">
                <span class="contacts">
                    <span class="name">
                        <i class="fa fa-phone" aria-hidden="true"></i>
                        <span>Biziň Bilen habarlaşyň:</span>
                    </span>
                    <span class="info">
                        +90 552 848 16 09
                    </span>
                </span>
                <span class="contacts">
                    <span class="name">
                        <i class="fa fa-mai" aria-hidden="true"></i>
                        <span>Elektron Poçta:</span>
                    </span>
                    <span class="info">
                        info@webigem.com
                    </span>
                </span>
            </div>

            <div class="wrapper">
                <span class="language">
                    <i class="fa fa-globe" aria-hidden="true"></i>
                    Türkmençe (TKM)
                </span>
                <ul class="currency-list">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle currency" data-toggle="dropdown">
                            <i class="fa fa-tmt" aria-hidden="true">TMT</i>
                        </a>
             
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="header">
        <div class="container">
            <div class="wrapper">
                <a href="/" class="logo">
                    <img src="~/Content/Images/Logo Update-01.png" alt="logo">
                </a>
                <button type="button" data-toggle="collapse" data-target="#header" aria-expanded="false"
                        class="navbar-toggle">
                    <i class="fa fa-bars" aria-hidden="true"></i>
                </button>
                <div class="menu-list">
                    <div id="header" class="navbar-collapse collapse">

                        <ul>

                            <li>
                                <a href="#">
                                    Bidirişler
                                </a>
                                <ul class="sub-menu small">
                                    <li>
                                        <ul>
                                            <li>
                                               Bidiriş Görnişleri
                                            </li>
                                            <li>
                                                <a href="/Home/Tumilanlar">
                                                    Hemme Bildirişler
                                                </a>
                                            </li>
                                            <li>
                                                <a href="/Home/Satilikilan">
                                                    Satuw Bildirişleri
                                                </a>
                                            </li>
                                            <li>
                                                <a href="/Home/Kiralikilan">
                                                    Kärende Bildirişleri
                                                </a>
                                            </li>

                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="subscribe-buttons">
                    <a href="/MGiris/Index">
                        <button class="sign-in js-sign-in">

                            <i class="fa fa-sign-in" aria-hidden="true"></i>

                            <span>Girmek</span>

                        </button>
                    </a>
                    <button class="registration">
                        <i class="fa fa-user" aria-hidden="true"></i>
                        <span>Bildiriş</span>
                    </button>
                </div>
            </div>
        </div>
    </div>

  
    @*Slider Partial Kısmı Burası da Çalışıyor *@

    @*@Html.Partial("~/Views/Home/Partials/_SliderPartial.cshtml")*@

    <div class="container js-home-3-search">
        <!--PROPERTY SEARCH FORM BEGIN-->
        <!--   Html.Action("ilanAra", "ilanlar")-->
        @*@Html.Action("ilanAra", "Home")*@



        <!--PROPERTY SEARCH FORM END-->
    </div>


    @RenderBody()

    <!--CALL TO ACTION2 END   Footer Kımıs -->
    @Html.Partial("~/Views/Home/Partials/_FooterPartial.cshtml")

    <script src="https://code.jquery.com/jquery-3.2.1.js" crossorigin="anonymous"></script> <!--Filtreleme için gerekli-->
    @*<script type="text/javascript" src="~/area/js/library/jquery.js"></script>*@
    <script type="text/javascript" src="~/area/js/library/bootstrap.js"></script>
    <script type="text/javascript" src="~/area/js/library/owl.carousel.js"></script>
    @*<script type="text/javascript" src="~/area/js/library/markerclusterer.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/library/ion.rangeSlider.min.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/library/jquery.mousewheel.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/library/chartist.min.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/library/microplugin.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/library/sifter.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/library/selectize.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/library/progressbar.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/library/module.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/library/hotkeys.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/library/uploader.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/library/simditor.js"></script>*@

    <script type="text/javascript" src="~/area/js/rangeslider.js"></script>
    @*<script type="text/javascript" src="~/area/js/agent_slider.js"></script>*@
    <script type="text/javascript" src="~/area/js/post_slider.js"></script>
    <script type="text/javascript" src="~/area/js/property_carousel.js"></script>
    @*<script type="text/javascript" src="~/area/js/partner_carousel.js"></script>*@
    <script type="text/javascript" src="~/area/js/agents_carousel.js"></script>
    <script type="text/javascript" src="~/area/js/counters.js"></script>
    <script type="text/javascript" src="~/area/js/slider_text.js"></script>
    @*<script type="text/javascript" src="~/area/js/pageviews_chart.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/search_form.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/search_form_slider.js"></script>*@
    <script type="text/javascript" src="~/area/js/count_checker.js"></script>
    @*<script type="text/javascript" src="j~/area/s/form_toggle.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/featured_carousel.js"></script>*@
    <script type="text/javascript" src="~/area/js/one_element_slider.js"></script>
    @*<script type="text/javascript" src="~/area/js/accordion.js"></script>*@
    <script type="text/javascript" src="~/area/js/partners_small.js"></script>
    @*<script type="text/javascript" src="~/area/js/pageviews_chart.js"></script>*@ 
    @*<script type="text/javascript" src="~/area/js/intro_page.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/map_component.js"></script>*@
    <script type="text/javascript" src="~/area/js/header.js"></script>
    <script type="text/javascript" src="~/area/js/property_slider.js"></script>
    <script type="text/javascript" src="~/area/js/visible.js"></script>
    @*<script type="text/javascript" src="~/area/js/coming-soon.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/rate_article.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/service-page-size.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/preloader.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/clear_form.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/property_gallery.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/area_tabs.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/testimonials.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/sign_in.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/account_page.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/chat_component.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/account_chart.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/account_component.js"></script>*@
    @*<script type="text/javascript" src="~/area/js/text_editor.js"></script>*@
    <script type="text/javascript" src="~/area/js/main.js"></script>
    <!--<script type="text/javascript" src="js-min/min.js"></script>-->

</body>


</html>