GGYatirim/Controllers/KullaniciController.cs
using GGYatirim.Models.Sinif;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Security;

namespace GGYatirim.Controllers
{
    public class KullaniciController : Controller
    {
        GYatirimEntities dr = new GYatirimEntities();

        // GET: Kullanici
        public ActionResult Index()
        {
            return View();
        }



        public ActionResult Kullaniciilan(int id)
        {


            var mail = (string)Session["EPosta"];
            var kullaniciilansayi = dr.Dbilan.Where(k => k.KullaniciNo == mail && k.Durum == true).Count();
            ViewBag.adsoyad = kullaniciilansayi;

          
            var kullaniciilan = dr.Dbilan.Where(k => k.KullaniciNo == mail && k.Durum == true).ToList();
           // ViewBag.adsoyad = kullaniciilan;


            return View(kullaniciilan);
            //  var deger = dr.Dbilan.Where(k => k.Durum == true).OrderByDescending(u => u.ilanID).ToList();
            //var deger1 = dr.DbKullanici.Where(k => k.Durum == true).OrderByDescending(u => u.KullaniciID).ToList();
            //var deger2 = dr.DbHareket.OrderByDescending(u => u.HareketID).ToList();
            //if (true)
            //{

            //}
            // var deger = dr.DbHareket.Where(k => k.KullaniciIDD==id).Where(f=>f.HaraketilanIDD==id).OrderByDescending(u => u.HareketID).ToList();
            //   var deger = dr.DbKullanici.Where(k => k.id==id).OrderByDescending(u => u.HareketID).ToList();
            //  var deger = dr.DbHareket.Where(f => f.HaraketilanIDD == id).ToList();

        }



        // Musteri Profil Göster
        public ActionResult MProfilList()
        {

            var mail = (string)Session["EPosta"];
            var adsoyad = dr.DbKullanici.Where(k => k.EPosta == mail && k.Durum == true).ToList();


            // İlan Sayısı
            var toplamilan = dr.Dbilan.Where(k => k.EPosta == mail && k.Durum == true).Count();
            ViewBag.toplamilan = toplamilan;

             // İlan Sayısı
            var onaybekleyenilan = dr.Dbilan.Where(k => k.EPosta == mail && k.MOnay == false).Count();
            ViewBag.onaybekleyenilan = onaybekleyenilan;



            //  var ilan = dr.Dbilan.Where(k => k.EPosta == mail && k.Durum == true).Where(d=>d.).ToList();
            //    ViewBag.ilan = ilan;

            return View(adsoyad);
        }



        // Müşteri Profil Güncelle

        // Getir

        public PartialViewResult MuteriGetr()
        {

            var mail = (string)Session["EPosta"];
            var id = dr.DbKullanici.Where(k => k.EPosta == mail && k.Durum == true).Select(k => k.KullaniciID).FirstOrDefault();
            var urngetr = dr.DbKullanici.Find(id);
            return PartialView("MuteriGetr", urngetr);
        }

        // Güncellle

        public ActionResult MusteriGuncelle(DbKullanici u, HttpPostedFileBase File)
        {
            if (ModelState.IsValid)
            {

                if (File != null)
                {
                    FileInfo fileinfo = new FileInfo(File.FileName);
                    WebImage img = new WebImage(File.InputStream);
                    string uzanti = (Guid.NewGuid().ToString() + fileinfo.Extension).ToLower();
                    //img.Resize(225, 180, false, false);
                    string tamyol = "~/ilanResimler/" + uzanti;
                    img.Save(Server.MapPath(tamyol));
                    u.Resim = "/ilanResimler/" + uzanti;

                }





                TempData["bilgiguncelle"] = "";

                var value = dr.DbKullanici.Find(u.KullaniciID);
                value.KisiAdi = u.KisiAdi;
                value.KisiSoyadi = u.KisiSoyadi;
                //   value.EPosta = u.EPosta;
                value.Sifre = u.Sifre;
                value.Meslek = u.Meslek;
                value.Telefon = u.Telefon;
                value.KisaAciklama = u.KisaAciklama;
                value.Face = u.Face;
                value.instagram = u.instagram;
                value.Sehir = u.Sehir;
                value.TamAdres = u.TamAdres;
                if (u.Resim != null)
                {
                    value.Resim = u.Resim;
                }
                value.Durum = true;
                //value.AdminYetki.id = u.id;
                dr.SaveChanges();
                return RedirectToAction("Index", "GGKPanel");
               // return RedirectToAction("MProfilList");
            }
            return View();
        }

        // Hesabımı Sil
        // Müşteri Hesabı Kalıcı Olarak Silinecektir
        ////  Sil
        ///
        public ActionResult HesabimiSil(int id)
        {
            var urnsil = dr.DbKullanici.Find(id);
            urnsil.Durum = false;
            dr.SaveChanges();
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }



    }
}

GGYatirim/Views/Kullanici/Kullaniciilan.cshtml
@{
    ViewBag.Title = "Kullaniciilan";
    Layout = "~/Views/Shared/_KullaniciLayout.cshtml";
}

<h2>Kullaniciilan</h2>

GGYatirim/Views/Kullanici/MProfilList.cshtml
@model IEnumerable<GGYatirim.Models.Sinif.DbKullanici>
@{
    ViewBag.Title = "MProfilList";
    Layout = "~/Views/Shared/_KullaniciLayout.cshtml";
}






<!doctype html>
<html class="no-js " lang="en">

<body class="theme-blue">


    <!-- Overlay For Sidebars -->
    <div class="overlay"></div>

    <!-- Top Bar -->
    <!-- Left Sidebar -->
    <!-- Chat-launcher -->

    <br /><br />
    <section class="content profile-page">

        @foreach (var x in Model)
        {

            <div class="container-fluid">
                <div class="row clearfix">
                    <div class="col-lg-4 col-md-12">


                        <div class="card member-card">
                            <div class="header l-cyan">
                                <h4 class="m-t-10">@x.KisiAdi @x.KisiSoyadi </h4>
                            </div>
                            <div class="member-img">
                                <a href="#" class="">

                                    @if (x.Resim == null)
                                    {
                                        <img src="~/KProfil/assets/images/profile_av.jpg" class="rounded-circle" alt="profile-image">

                                    }
                                    else
                                    {
                                        <img src="@x.Resim" class="rounded-circle" alt="profile-image">

                                    }
                                </a>
                            </div>
                            <div class="body">
                                <div class="col-12">
                                    <ul class="social-links list-unstyled">
                                        <li><a title="facebook" href="@x.Face"><i class="zmdi zmdi-facebook"></i></a></li>
                                        @*<li><a title="twitter" href="#"><i class="zmdi zmdi-twitter"></i></a></li>*@
                                        <li><a title="instagram" href="@x.instagram"><i class="zmdi zmdi-instagram"></i></a></li>
                                    </ul>
                                    <p class="text-muted">@x.Meslek</p>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-4">
                                        <h5>@ViewBag.toplamilan</h5>
                                        <small>İlan Sayisi</small>
                                    </div>

                                    <div class="col-8">
                                        <h5>@ViewBag.onaybekleyenilan</h5>
                                        <small>Onay Bekleyen İlan Sayısı</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card">
                            <ul class="nav nav-tabs">
                                <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#about">Bigilerim</a></li>
                                <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#friends">Parola Şifre</a></li>
                            </ul>
                            <div class="tab-content">


                                <div class="tab-pane body active" id="about">

                                    <small class="text-muted">Adres: </small>
                                    <p>@x.TamAdres</p>
                                    <hr>
                                    <small class="text-muted">Facebook: </small>
                                    <p>@x.Face</p>
                                    <hr>
                                    <small class="text-muted">Instagram: </small>
                                    <p>@x.instagram</p>
                                    <hr>
                                    <small class="text-muted">Kısa Açıklama: </small>
                                    <p>@x.KisaAciklama</p>
                                    <hr>
                                    <small class="text-muted">Kayıt Tarihiniz: </small>
                                    <p>@Convert.ToDateTime(x.Tarih).ToString("dd/MMM/yyyy")</p>
                                    <hr>

                                </div>



                                <div class="tab-pane body" id="friends">

                                    <small class="text-muted">Müşteri No: </small>
                                    <p>@x.KullaniciNo</p>
                                    <hr>
                                    <small class="text-muted">E Posta: </small>
                                    <p>@x.EPosta</p>
                                    <hr>
                                    <small class="text-muted">Şifre: </small>
                                    <p>@x.Sifre</p>
                                    <hr>
                                    <small class="text-muted">Telefon: </small>
                                    <p>@x.Telefon</p>
                                    <hr>
                                    <small class="text-muted">Şehir: </small>
                                    <p>@x.Sehir</p>
                                    <hr>

                                </div>
                            </div>
                        </div>

                    </div>


                    <!--Dekldelkd ewşd wlkednw-->
                    <div class="col-lg-8 col-md-12">
                        <div class="card">
                            <ul class="nav nav-tabs">

                                <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#usersettings">Profil Ayarları</a></li>
                                <a class="btn btn-default btn-round btn-danger" onclick="return confirm('Hesabınız Kalıcı Olarak Silinecektir! Hesabınızı Silmek İstediginizden Emin misiniz? @x.KisiAdi @x.KisiSoyadi ')" data-toggle="~/Kullanici/HesabimiSil/@x.KullaniciID" href="~/Kullanici/HesabimiSil/@x.KullaniciID">Hesabımı Sil</a>

                            </ul>
                        </div>
                        <div class="tab-content">

                            <div role="tabpanel" class="tab-pane blog-page active" id="usersettings">
                                <div class="card">
                                    <div class="header">
                                        <h2><strong>Hesap</strong> Ayarları</h2>
                                    </div>
                                    @Html.Action("MuteriGetr", "Kullanici")

                                </div>

                            </div>
                        </div>
                    </div>




                </div>
            </div>

        }
    </section>

</body>
</html>

GGYatirim/Views/Kullanici/MuteriGetr.cshtml
@model GGYatirim.Models.Sinif.DbKullanici
@{
    //ViewBag.Title = "MuteriGetr";
    Layout = "~/Views/Shared/_KullaniciLayout.cshtml";
}






@using (Html.BeginForm("MusteriGuncelle", "Kullanici", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="body">

        <div class="row clearfix">
            <div class="col-lg-6 col-md-12">
                <a href="#">Adınız</a>
                <div class="form-group">
                    @Html.TextBoxFor(x => x.KisiAdi, new { @class = "form-control" })
                    @*<input type="text" name="" class="form-control" placeholder="First Name">*@
                </div>
            </div>
            <div class="col-lg-6 col-md-12">
                <a href="#">Soyadınız</a>
                <div class="form-group">
                    @Html.TextBoxFor(x => x.KisiSoyadi, new { @class = "form-control" })

                    @*<input type="text" class="form-control" placeholder="Last Name">*@
                </div>
            </div>
            <div class="col-lg-6 col-md-12">
                <a href="#">Mesleğiniz</a>
                <div class="form-group">
                    @Html.TextBoxFor(x => x.Meslek, new { @class = "form-control" })

                    @*<input type="text" class="form-control" placeholder="City">*@
                </div>
            </div>
            <div class="col-lg-6 col-md-12">
                <a href="#">Şifre</a>
                <div class="form-group">
                    @Html.TextBoxFor(x => x.Sifre, new { @class = "form-control", type = "password" })

                    @*<input type="text" class="form-control" placeholder="E-mail">*@
                </div>
            </div>
            <div class="col-lg-6 col-md-12">
                <a href="#">Telefon No</a>
                <div class="form-group">
                    @Html.TextBoxFor(x => x.Telefon, new { @class = "form-control", type = "tel" })

                    @*<input type="text" class="form-control" placeholder="Country">*@
                </div>
            </div>

            <div class="col-lg-6 col-md-12">
                <a href="#">Şehir</a>
                <div class="form-group">
                    @Html.TextBoxFor(x => x.Sehir, new { @class = "form-control" })

                    @*<input type="text" class="form-control" placeholder="E-mail">*@
                </div>
            </div>

            <div class="col-lg-6 col-md-12">
                <a href="#">Tam Adres</a>
                <div class="form-group">
                    @Html.TextBoxFor(x => x.TamAdres, new { @class = "form-control" })

                    @*<input type="text" class="form-control" placeholder="E-mail">*@
                </div>
            </div>





            <div class="col-lg-6 col-md-12">
                <a href="#">Facebook</a>
                <div class="form-group">
                    @Html.TextBoxFor(x => x.Face, new { @class = "form-control" })

                    @*<input type="text" class="form-control" placeholder="E-mail">*@
                </div>
            </div>

            <div class="col-lg-6 col-md-12">
                <a href="#">Instagram</a>
                <div class="form-group">
                    @Html.TextBoxFor(x => x.instagram, new { @class = "form-control" })

                    @*<input type="text" class="form-control" placeholder="E-mail">*@
                </div>
            </div>

            <div class="col-lg-6 col-md-12">
                <a href="#">Profilinizi Seçiniz</a>
                <div class="form-group">
                    <input type="file" id="File" name="File" accept=".jpg,.JPG,.PNG,.png,.jpeg,.JPEG" class="form-control" />

                    @*<input type="text" class="form-control" placeholder="E-mail">*@
                </div>
            </div>



            <div class="col-md-12">
                <div class="form-group">
                    <a href="#">Kısaca Kendinden Bahset</a>
                    @Html.TextAreaFor(x => x.KisaAciklama, new { @class = "form-control no-resize" })

                    @*<textarea rows="4" class="form-control no-resize" placeholder="Address Line 1"></textarea>*@
                </div>
            </div>
            @Html.HiddenFor(x => x.KullaniciID)
            <div class="col-md-12">
                <button class="btn btn-primary btn-round">Değişiklikleri Kaydet</button>
            </div>
        </div>

    </div>
}


<script src="~/KProfil/assets/bundles/libscripts.bundle.js"></script> <!-- Lib Scripts Plugin Js ( jquery.v3.2.1, Bootstrap4 js) -->




<script src="~/KProfil/assets/bundles/mainscripts.bundle.js"></script>